# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Runnable Blog
email: support@runnable.com
description: > # this means to ignore newlines until "baseurl:"
  The official engineering blog from the team at Runnable
url: https://runnable.com # the base hostname & protocol for your site
baseurl: /blog
twitter:
  username: GetRunnable
facebook:
  publisher: Runnable

seo:
  type: blog

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-timeago

permalink: /:title
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
  -
    scope:
      path: ""
      type: "posts"
    values:
      seo:
        type: blog

sass:
  sass_dir: _sass/

jekyll_timeago:
  depth: 1 # Level of detail
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: 'ago'
  prefix: ''
  suffix_future: ''
  prefix_future: 'in'
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'

paginate: 8
paginate_path: "/:num/"
