# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Runnablog
email: blog@runnable.com
description: > # this means to ignore newlines until "baseurl:"
  The official blog from the team at Runnable
url: https://runnable.com # the base hostname & protocol for your site
baseurl: /blog
twitter:
  username: GetRunnable
facebook:
  publisher: Runnable

seo:
  type: blog

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:title
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
  -
    scope:
      path: ""
      type: "posts"
    values:
      seo:
        type: blog

sass:
  sass_dir: _sass/

paginate: 8
paginate_path: "/:num/"
